import { StyleSheet, StatusBar } from 'react-native';

const styles =  StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#87CEFA',
  },
  cadastro: {
    flexDirection: 'row',
  },
  titulo: {
    fontSize: 30,
    marginBottom: 50,
  },
  picker: {
    borderWidth: 2,
    borderColor: '#00008B',
    borderRadius: 4,
    height: '10%',
    width: '45%',
    margin: 10,
  },
  scrollView: {    
    backgroundColor: '#87CEFA',
    height:'0%',
  },
  botao: {
    width: 120,
    height: 40,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
    borderRadius: 5,
  },
  textoBotao: {
    color: '#fff',
  },
  inputNome: {
    width: '45%',
    borderColor: '#FF1493',
    color: '#8B008B',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  inputCodigo: {
    width: '20%',
    borderColor: '#FF1493',
    color: '#8B008B',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  inputEstoque: {
    width: '25%',
    borderColor: '#FF1493',
    color: '#8B008B',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  inputCheck: {
    width: '10%',
    borderColor: '#FF1493',
    color: '#8B008B',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  caixaTexto: {
    borderColor: "#00008B",
    borderWidth: 2,
    height: 40,
    width: '100%',
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  contato: {
    backgroundColor: '#F33232',
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    margin: 5,
    borderRadius: 5,
    shadowColor: "#000",
    shadowOffset: {
        width: 0,
        height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
},
produtoAtivo: {
  backgroundColor: '#9EF116',
  flexDirection: 'row',
  height: 50,
  alignItems: 'center',
  margin: 5,
  borderRadius: 5,
  shadowColor: "#000",
  shadowOffset: {
      width: 0,
      height: 1,
  },
  shadowOpacity: 0.22,
  shadowRadius: 2.22,
  elevation: 3,
},
produtoInativo: {
  backgroundColor: '#C4BBBB',
  flexDirection: 'row',
  height: 50,
  alignItems: 'center',
  margin: 5,
  borderRadius: 5,
  shadowColor: "#000",
  shadowOffset: {
      width: 0,
      height: 1,
  },
  shadowOpacity: 0.22,
  shadowRadius: 2.22,
  elevation: 3,
},
filtros:{ 
  width: '100%',
  flexDirection: 'row',
  borderRadius: 5,
  borderColor: 'red',
  borderStyle: 'solid'
},
filtroBotaoTds:{
  width: 80,
  height: 40,
  backgroundColor: '#FFF',
  justifyContent: 'center',
  alignItems: 'center',
  margin: 5,
  borderRadius: 5,
},
filtroBotaoAtivo:{
  width: 80,
  height: 40,
  backgroundColor: '#90EE90',
  justifyContent: 'center',
  alignItems: 'center',
  margin: 5,
  borderRadius: 5,
},
filtroBotaoInativo:{
  width: 80,
  height: 40,
  backgroundColor: '#C4BBBB',
  justifyContent: 'center',
  alignItems: 'center',
  margin: 5,
  borderRadius: 5,
},

filtroBotaoQtde:{
  width: '65%',
  height: 40,
  backgroundColor: 'red',
  justifyContent: 'center',
  alignItems: 'center',
  margin: 5,
  borderRadius: 5,
},
textoFiltro:{
  color: '#000',
}

});

export default styles;